INTENT_LIFETIME_SECONDS = 15 * 60
HISTORY_PAGE_SIZE = 10
WALLET_SUMMARY_COOLDOWN_SECONDS = 10
WALLET_HISTORY_COOLDOWN_SECONDS = 15
WALLET_PROVIDER_COOLDOWN_SECONDS = 10
WALLET_RPC_COOLDOWN_SECONDS = 5
HISTORY_NEXT_COOLDOWN_SECONDS = 3
